### ISSUE TITLE
Question about parameter and MapToPoint

### ISSUE THREAD

**Issue by MoienBowen** [elliptic-shiho/ecpy#10]
**Parameter**

In the file "https://github.com/elliptic-shiho/ecpy/blob/master/examples/boneh_lynn_shacham_short_signature.py", I would like to know why you have all those parameters please?

In your "https://github.com/elliptic-shiho/ecpy/blob/master/ecpy/elliptic_curve/EllipticCurveRepository.py" nor https://safecurves.cr.yp.to has that specific number (p, l, etc.). I even did not found them on Google.

**MapToPoint**

I tried to replace all those parameter with yours (for example: (F, E, G, n) = EllipticCurveRepository("secp521r1")).

In addition, I tried to replace FiniteField with ExtendedFiniteField + both possible functions.

None of those works with MapToPoint.

Case FiniteField:

MapToPoint(E, E.field(12313))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ecpy/elliptic_curve/pairing.py", line 116, in MapToPoint
    x = cubic_root(y**2 - 1)
  File "/usr/local/lib/python2.7/site-packages/ecpy/utils/root.py", line 183, in cubic_root
    rho = F(random.randint(1, p - 1), random.randint(1, p - 1))
  File "/usr/local/lib/python2.7/site-packages/ecpy/rings/Ring.py", line 12, in __call__
    return s.element_class(s, *x)
TypeError: __init__() takes exactly 3 arguments (4 given)

Case ExtendedFiniteField:

MapToPoint(E, E.field(hash_ID))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ecpy/elliptic_curve/pairing.py", line 117, in MapToPoint
    Q = E(x, y)
  File "/usr/local/lib/python3.7/site-packages/ecpy/elliptic_curve/EllipticCurve.py", line 78, in __call__
    return s.element_class(s, *x)
  File "/usr/local/lib/python3.7/site-packages/ecpy/elliptic_curve/EllipticCurve.py", line 354, in __init__
    raise ArithmeticError("Invalid Point: (%s, %s, %s)" % (s.x, s.y, s.z))
ArithmeticError: Invalid Point: (mpz(37625453826780433377388048957201879362379477227012885069949001701454994121997751017162539005563127226988793675695228), mpz(12847647103851729428361901244548237337583883889892318731641379765076369134081500062657316972842886439414859445286270), 1)

**Comment by elliptic-shiho** [comment]
@n00d1e5 I was referenced "An example of construction of pairing-friendly supersingular elliptic curve" in [1] and its (maybe?) original definition in [2], to write these codes. this parameter was generated by ecpy. I didn't refered other ones.

So ecpy's `MapToPoint` function has some restriction. for example, the curve must be `y^2 = x^3 + 1` and its order must equal to `p+1` (this is equivalent to it must be a supersingular elliptic curve). thus It can't use for your tested parameter.

If you need more deeper description, I recommend to read [2] and [3] (Especially Chapter XI. Algorithmic Aspects of Elliptic Curves, and Chapter III The Geometry of Elliptic Curves). 

[1]: TSUJII Shigeo, KASAHARA Masao, et al. 2008. 暗号理論と楕円曲線 (Japanese Book)
[2]: Dan Boneh and Matthew Franklin. 2003. [Identity-Based Encryption from the Weil Pairing](https://crypto.stanford.edu/~dabo/papers/bfibe.pdf)
[3]: Joseph H. Silverman. 2009. The Arithmetic of Elliptic Curves (2nd ed. )
